#! /bin/bash
#
# Compute curl of vectors field
# Curl(u,v) = v_x - u_y
#
# Dominique Béréziat (c) 2005
# $Id: vel2curl,v 1.2 2005/06/12 20:17:19 bereziat Exp $

TMP=/tmp/vel2curl$$
INPUT=$1
OUTPUT=${2--}

case $# in
    0)
	echo 'Compute curl of vectors field for displaying in xflow'
	echo 'Usage : vel2div input.uv [output.inr]'
	exit
	;;
    *)
	;;
esac

# Compute curl
extg -iv 2 -v 1 $INPUT | recfilters -cont 10 -s 1 -x 1 -y -1 -z -1 > $TMP-1.inr
extg -iv 1 -v 1 $INPUT | recfilters -cont 10 -s 1 -x -1 -y 1 -z -1 | bi -n -1 | ad $TMP-1.inr > $TMP-2.inr
set -- `ical $TMP-2.inr`
min=$1
max=$3
echo $1 $3

# Normalization and conversion to 1-byte
norma $TMP-2.inr | cco -f -hdr=8 - $OUTPUT
rm -f $TMP-1.inr $TMP-2.inr

# Color palet computing
echo "
m=$min
ma=$max
g=-m/(ma-m)*255
/* red component */
for( i=0; i<g; i++) {
  (g-i)/g
}
for( i=g; i<256; i++) {
  0
}
/* green component */
for( i=0;i<256;i++) {
  0
}
/* blue component */
for( i=0; i<g; i++) {
  0
}
for( i=g; i<256; i++) {
  (i-g)/(255-g)
}
" | bc -l  | cim -x 256 -y 3 -f=%f > $TMP-pal.inr

ifmt -setct  $TMP-pal.inr $OUTPUT
rm -f $TMP-pal.inr

