/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_xflow_mainwindow (void);
GtkWidget* create_winprefs (void);
GtkWidget* create_export (void);
GtkWidget* create_xflow_info (void);
GtkWidget* create_alert_newversion (void);
GtkWidget* create_legendes (void);
GtkWidget* create_winprefs_V2 (void);
